### ISSUE TITLE
NPE when mirroring http://archive.eclipse.org/technology/babel/update-site/R0.15.1/oxygen

### ISSUE THREAD

**Issue by pms1** [pms1/tppt#47]
Mirroring of http://archive.eclipse.org/technology/babel/update-site/R0.15.1/oxygen does not work.

The mirror list returned by

http://www.eclipse.org/downloads/download.php?file=/technology/babel/update-site/R0.15.1/oxygen/&format=xml&countryCode=us&timeZone=1&format=xml

as of 2020-10-17 is bogus and does not contain valid URIs:

` <mirror url="/technology/babel/update-site/R0.15.1/oxygen/" label="[]  ()" />`

This causes an exception in p2:

`!ENTRY org.eclipse.osgi 4 0 2020-10-17 10:25:01.139
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:713)
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.downloadArtifact(SimpleArtifactRepository.java:640)
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getRawArtifact(SimpleArtifactRepository.java:782)
        at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository.getRawOrNormalArtifact(CompositeArtifactRepository.java:387)
        at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository.getRawArtifact(CompositeArtifactRepository.java:379)
        at org.eclipse.equinox.internal.p2.artifact.repository.RawMirrorRequest.getArtifact(RawMirrorRequest.java:94)
        at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transferSingle(MirrorRequest.java:286)
        at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transfer(MirrorRequest.java:222)
        at org.eclipse.equinox.internal.p2.artifact.repository.RawMirrorRequest.perform(RawMirrorRequest.java:55)
        at org.eclipse.equinox.p2.internal.repository.mirroring.Mirroring.downloadArtifact(Mirroring.java:225)
        at org.eclipse.equinox.p2.internal.repository.mirroring.Mirroring.mirror(Mirroring.java:180)
        at org.eclipse.equinox.p2.internal.repository.mirroring.Mirroring.run(Mirroring.java:111)
        at com.github.pms1.tppt.mirror.MirrorApplication.start(MirrorApplication.java:428)
`

This is more a bug in the eclipse.org server infrastructure and/or p2 and not tppt, but may be can be mitigated by tppt.

**Comment by pms1** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=567962
